### ISSUE TITLE
C-a when soft wrapping

### ISSUE THREAD

**Issue by emkayonline** [jonhiggs/vim-readline#6]
Nice plugin. though I have noticed that C-a moves to the first character in the line, not the first character in the visible line when lines are wrapped.

Would it be possible for the plugin to detect this and use 0 rather than ^ to move to the start of the line?

**Comment by jonhiggs** [comment]
Would you mind trying out that fix for me and letting me know if it solves your issue?

**Comment by emkayonline** [comment]
That is spot on!

Thank you.
